services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sitstraight_network
    restart: unless-stopped

  ml-client:
    build: ./machine-learning-client
    container_name: ml-client
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://jrc9921_db_user:8TWi5FMHWdyRWDkA@cluster0.nzniema.mongodb.net/?appName=Cluster0
    depends_on:
      - mongodb
    networks:
      - sitstraight_network
    restart: unless-stopped

  web:
    build: ./web-app
    container_name: web-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://jrc9921_db_user:8TWi5FMHWdyRWDkA@cluster0.nzniema.mongodb.net/?appName=Cluster0
      - FLASK_SECRET_KEY=dev_secret_change_in_production
      - ML_CLIENT_URL=http://ml-client:5002
    depends_on:
      - ml-client
      - mongodb
    networks:
      - sitstraight_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  sitstraight_network:
    driver: bridge
